export const SETTINGS_GETALL_REQUEST = 'SETTINGS_GETALL_REQUEST';
export const SETTINGS_GETALL_SUCCESS = 'SETTINGS_GETALL_SUCCESS';
export const SETTINGS_GETALL_FAILURE = 'SETTINGS_GETALL_FAILURE';

export const SETTINGS_UPDATE_REQUEST = 'SETTINGS_UPDATE_REQUEST';
export const SETTINGS_UPDATE_SUCCESS = 'SETTINGS_UPDATE_SUCCESS';
export const SETTINGS_UPDATE_FAILURE = 'SETTINGS_UPDATE_FAILURE';

export const STOCKS_GETALL_REQUEST = 'STOCKS_GETALL_REQUEST';
export const STOCKS_GETALL_SUCCESS = 'STOCKS_GETALL_SUCCESS';
export const STOCKS_GETALL_FAILURE = 'STOCKS_GETALL_FAILURE';

export const STOCKS_CREATE_REQUEST = 'STOCKS_CREATE_REQUEST';
export const STOCKS_CREATE_SUCCESS = 'STOCKS_CREATE_SUCCESS';
export const STOCKS_CREATE_FAILURE = 'STOCKS_CREATE_FAILURE';